version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=MP77
      - POSTGRES_PASSWORD=IDecreeAndDeclareWarOnShitePerformance
      - POSTGRES_DB=hvalfangst_db
    ports:
      - '5432:5432'
    networks:
      - hvalfangstnettverket

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - hvalfangstnettverket

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hvalfangstnettverket
    depends_on:
      - db
      - redis
    ports:
      - "1911:1911"

volumes:
  postgres_data:
  redis:
  redis-config:

networks:
  hvalfangstnettverket:
    driver: bridge
